version: '3'
services:
  web:
    build: .
    image: 517252388151.dkr.ecr.us-east-1.amazonaws.com/sketch-dn-ht:latest
    ports:
    - "${PORT-0}:8000"
    volumes:
      - yarn_cache:/usr/local/share/.cache/yarn
volumes:
  yarn_cache:
